### ISSUE TITLE
month without brackets is added to authors

### ISSUE THREAD

**Issue by victor-moreno** [kamapu/biblio#34]
Hi,
zotero bibtext format will export, for example month = mar after author = { .... }, 

Then, when read into R "month = mar" is appended to last author.
It seems this syntax is correct bibtex
https://forums.zotero.org/discussion/71725/solved-bibtex-export-and-curly-brackets

**Comment by kamapu** [comment]
Sorry @victor-moreno for ignoring this issue. As I see it, it is some kind of format inconsistency. Since I have reactivated the development of this package, I will try to fix this as soon as possible.
