### ISSUE TITLE
Add easy way to extract bibtex by keys

### ISSUE THREAD

**Issue by SimonGreenhill** [kamapu/biblio#41]
Currently the only way to access the bibtex information for a key is:

```{r}
bib <- read_bib(...)
b <- bib[bib$bibtexkey == 'MYKEY,]
```

It would be very nice to be able to do this:

```{r}
bib['MYKEY']
```

**Comment by kamapu** [comment]
The **lib_df** class inherits methods from **data.frame**, so your example is used to index columns rather than rows. To select references there is a `subset()` method.

```r
Refs <- read_bib(x = file.path(path.package("biblio"), "LuebertPliscoff.bib"))
as.data.frame(subset(Refs, bibtexkey == "ravenna2000"))
```
